name: Long Running Workflow

on:
  workflow_dispatch:

jobs:
  long-running-job:
    runs-on: ubuntu-latest
    timeout-minutes: 1440  # 24 hours

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run a long task
      run: |
        echo "Starting a long-running task"
        sleep 72000  # Sleep for 20 hours
        echo "Completed the long-running task"
